//Extra Credit Assignment 2.6
/* In this extra credit assignment, I will write a program that will calculate
the amount of revenue the East Coast sales division will generate if they generate 62% of a $4.6 million
dollar sales revenue. **/

public class EastCoastSales
{
   public static void main(String[] args)
   {
      final float salesPercent = .62f;
      final int revenue = 4600000;
      float revenuePredict = revenue * salesPercent;
      
      System.out.println("The East Coast sales division has generated " + salesPercent + ". Based on");
      System.out.println("these sales, a reasonable prediction of the amount of sales generated by");
      System.out.println("East Coast in a $4.6 million revenue would be " + revenuePredict + ".");
   }
}